# Generated by Django 5.1.5 on 2025-01-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
