# Generated by Django 5.1.5 on 2025-01-24 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoredStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='BR1', max_length=150)),
                ('upper_tunnel_bound', models.IntegerField()),
                ('lower_tunnel_bound', models.IntegerField()),
                ('periodicity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StockUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.monitoredstock')),
            ],
        ),
    ]
