# Generated by Django 5.1.5 on 2025-01-25 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_remove_monitoredstock_slug_monitoredstock_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitoredstock',
            old_name='author',
            new_name='user',
        ),
    ]
