# Generated by Django 5.1.5 on 2025-02-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_alter_monitoredstock_lower_tunnel_bound_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoredstock',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
