services:
  django:
    container_name: django
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=127.0.0.1
      - CELERY_BROKER=redis://redis:6379/0
    depends_on:
      - redis

  celery-worker:
    build: .
    command: celery -A core worker --loglevel=info
    volumes:
      - .:/usr/src/app
    depends_on:
      - django
      - redis

  celery-beat:
    build: .
    command: celery -A core beat --loglevel=info
    volumes:
      - .:/usr/src/app
    depends_on:
      - celery-worker
      - django
      - redis

  redis:
    image: "redis:alpine"
